spring:
  config:
    import: optional:file:.env[.properties]
  # Database Configuration
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

  # Flyway Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: visittracker
    validate-on-migrate: true

# Server Configuration
server:
  port: 8080

# Logging Configuration
logging:
  level:
    org:
      springframework: INFO
      flywaydb: DEBUG
    com:
      healthcare:
        visittracker: DEBUG
